#
# This roles generate CA & kubeconfig in deployer node
# deployer node send the CA & kubeconfig into all nodes
#
- name: generate certificate & kubeconfig
  become: yes
  hosts: deployer
  roles:
    - certificate-ca
    - certificate-etcd
    - certificate-master
    - certificate-worker

#
# data encryption for etcd
# https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/
#
- name: generate data-encryption
  become: yes
  hosts: deployer
  roles:
    - data-encryption

#
# This roles setup etcd cluster in etcd group ansible
# you can merge etcd into master
# by changing etcd group IP into master IP
#
- name: setup etcd cluster
  become: yes
  hosts: etcd
  roles:
    - kubernetes-etcd

#
# This roles setup haproxy keepalived in master node
# and setup master cluster
#
- name: setup master cluter
  become: yes
  hosts: master
  roles:
    - kubernetes-loadbalancer
    - kubernetes-master

#
# This roles setup worker cluster in master & worker node
#
- name: setup worker
  become: yes
  hosts: worker,master
  roles:
    - kubernetes-worker

#
# this roles setup CNI, DNS, and taint master node
#
- name: setup addons
  become: yes
  hosts: master
  roles:
    - kubernetes-addons
