---
- name: copy data encryption template
  template:
    src: "encryption-config.yml.j2"
    dest: "{{ kubernetes.certificate.directory }}/encryption-config.yml"

- name: copy into master node
  vars:
    master_ip: "{{ groups['master'] | join(' ') }}"
  args:
    chdir: "{{ kubernetes.certificate.directory }}"
  shell: |
    for instance in {{ master_ip }}; do
      sshpass -f ~/p scp encryption-config.yml {{ user }}@${instance}:~/
    done

  