# wget https://github.com/coreos/etcd/releases/download/v3.5.4/etcd-v3.5.4-linux-amd64.tar.gz
# tar -xvzf etcd-v3.5.4-linux-amd64.tar.gz -C /tmp/
# - name: Downlaod and Extract etcd-{{ kubernetes.components.etcd.version }}-linux-amd64.tar.gz into /tmp/
#   unarchive:
#     src: https://github.com/coreos/etcd/releases/download/{{ kubernetes.components.etcd.version }}/etcd-{{ kubernetes.components.etcd.version }}-linux-amd64.tar.gz
#     dest: /tmp/
#     remote_src: yes

# sudo tar -xvf cni-plugins-linux-amd64-v1.1.1.tgz -C /opt/cni/bin/
- name: This command will change the working directory to somedir/
  ansible.builtin.shell:
    cmd: etcd-{{ kubernetes.components.etcd.version }}-linux-amd64.tar.gz -C /tmp/


- name: Move etcd files
  copy:
    src: "/tmp/etcd-{{ kubernetes.components.etcd.version }}-linux-amd64/{{item}}"
    dest: "/usr/local/bin/{{item}}"
    remote_src: yes
    mode: 0544
  with_items:
  - etcd
  - etcdctl

- name: create etcd directory
  file:
    path: /etc/etcd
    state: directory

- name: create etcd directory
  file:
    path: /var/lib/etcd
    state: directory
    mode: 0700

- name: Copy cert
  copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
    mode: 400
  with_items:
    - { src: '/home/{{ user }}/etcd-ca.pem', dest: '/etc/etcd/etcd-ca.pem' }
    - { src: '/home/{{ user }}/kube-etcd.pem', dest: '/etc/etcd/kube-etcd.pem' }
    - { src: '/home/{{ user }}/kube-etcd-key.pem', dest: '/etc/etcd/kube-etcd-key.pem' }
    - { src: '/home/{{ user }}/kube-etcd-peer.pem', dest: '/etc/etcd/kube-etcd-peer.pem' }
    - { src: '/home/{{ user }}/kube-etcd-peer-key.pem', dest: '/etc/etcd/kube-etcd-peer-key.pem' }

- name: create etcd systemd unit file
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    mode: 644

- name: restart etcd
  systemd:
    name: etcd
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: setup cronjob to restart etcd daily
  cron:
    name: "restart-etcd"
    special_time: daily
    job: "systemctl restart etcd"
