# - name: create kubernetes directory
#   file:
#     path: /etc/kubernetes/config/
#     state: directory

# - name: create kubernetes directory
#   file:
#     path: /var/lib/kubernetes/
#     state: directory

# - name: create kubectl directory
#   file:
#     path: /root/.kube/
#     state: directory

# - name: Download and extract Kubernetes server
#   unarchive:
    # src: https://dl.k8s.io/{{ kubernetes.version }}/kubernetes-server-linux-amd64.tar.gz
    # dest: /opt/
    # remote_src: yes

# - name: install kubernetes service
#   copy:
#     src: "{{ item.src }}"
#     dest: "{{ item.dest }}"
#     mode: a+x
#     remote_src: yes
#   with_items:
#   - { src: '/opt/kubernetes/server/bin/kube-apiserver', dest: '/usr/local/bin/kube-apiserver' }
#   - { src: '/opt/kubernetes/server/bin/kube-controller-manager', dest: '/usr/local/bin/kube-controller-manager' }
#   - { src: '/opt/kubernetes/server/bin/kube-scheduler', dest: '/usr/local/bin/kube-scheduler' }
#   - { src: '/opt/kubernetes/server/bin/kubectl', dest: '/usr/local/bin/kubectl' }

- name: Copy cert
  copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
    mode: 400
  with_items:
    - { src: '/home/{{ user }}/etcd-ca.pem', dest: '/var/lib/kubernetes/etcd-ca.pem' }
    - { src: '/home/{{ user }}/kubernetes-ca.pem', dest: '/var/lib/kubernetes/kubernetes-ca.pem' }
    - { src: '/home/{{ user }}/kubernetes-ca-key.pem', dest: '/var/lib/kubernetes/kubernetes-ca-key.pem' }
    - { src: '/home/{{ user }}/kubernetes-front-proxy-ca.pem', dest: '/var/lib/kubernetes/kubernetes-front-proxy-ca.pem' }
    - { src: '/home/{{ user }}/kubernetes-service-account-management-ca.pem', dest: '/var/lib/kubernetes/kubernetes-service-account-management-ca.pem' }
    - { src: '/home/{{ user }}/kubernetes-service-account-management-ca-key.pem', dest: '/var/lib/kubernetes/kubernetes-service-account-management-ca-key.pem' }
    - { src: '/home/{{ user }}/kube-apiserver.pem', dest: '/var/lib/kubernetes/kube-apiserver.pem' }
    - { src: '/home/{{ user }}/kube-apiserver-key.pem', dest: '/var/lib/kubernetes/kube-apiserver-key.pem' }
    - { src: '/home/{{ user }}/kube-apiserver-etcd-client.pem', dest: '/var/lib/kubernetes/kube-apiserver-etcd-client.pem' }
    - { src: '/home/{{ user }}/kube-apiserver-etcd-client-key.pem', dest: '/var/lib/kubernetes/kube-apiserver-etcd-client-key.pem' }
    - { src: '/home/{{ user }}/kube-apiserver-kubelet-client.pem', dest: '/var/lib/kubernetes/kube-apiserver-kubelet-client.pem' }
    - { src: '/home/{{ user }}/kube-apiserver-kubelet-client-key.pem', dest: '/var/lib/kubernetes/kube-apiserver-kubelet-client-key.pem' }
    - { src: '/home/{{ user }}/front-proxy-client.pem', dest: '/var/lib/kubernetes/front-proxy-client.pem' }
    - { src: '/home/{{ user }}/front-proxy-client-key.pem', dest: '/var/lib/kubernetes/front-proxy-client-key.pem' }
    - { src: '/home/{{ user }}/kube-controller-manager.kubeconfig', dest: '/var/lib/kubernetes/kube-controller-manager.kubeconfig' }
    - { src: '/home/{{ user }}/kube-scheduler.kubeconfig', dest: '/var/lib/kubernetes/kube-scheduler.kubeconfig' }
    - { src: '/home/{{ user }}/admin.kubeconfig', dest: '/root/.kube/config' }
    - { src: '/home/{{ user }}/encryption-config.yml', dest: '/var/lib/kubernetes/encryption-config.yml' }

- name: create kubernetes service files
  template:
    src: "kube-scheduler.yml.j2"
    dest: "/etc/kubernetes/config/kube-scheduler.yml"

- name: create kubernetes service files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 644
  with_items:
    - { src: 'kube-controller-manager.service.j2', dest: '/etc/systemd/system/kube-controller-manager.service' }
    - { src: 'kube-apiserver.service.j2', dest: '/etc/systemd/system/kube-apiserver.service' }
    - { src: 'kube-scheduler.service.j2', dest: '/etc/systemd/system/kube-scheduler.service' }

- name: restart kube-apiserver
  systemd:
    name: kube-apiserver
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: restart kube-controller-manager
  systemd:
    name: kube-controller-manager
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: restart kube-scheduler
  systemd:
    name: kube-scheduler
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: setup cronjob to restart master daily
  cron:
    name: "restart-master"
    special_time: daily
    job: "systemctl restart kube-apiserver kube-controller-manager kube-scheduler"
