# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'


Vagrant.configure("2") do |config|
    
  ##### DEFINE VM #####
  config.vm.define "ubuntu-01" do |config|
    config.vm.hostname = "ubuntu-01"
    config.vm.box = "alvistack/ubuntu-22.04"
    config.vm.box_check_update = false
    #config.vm.network "private_network", ip: "192.168.18.9"
    config.vm.provider :libvirt do |v|
    v.memory = 1024
    end
  end
end